/*
@license
dhtmlxScheduler.Net v.3.3.0 

This software is covered by DHTMLX Evaluation License. Contact sales@dhtmlx.com to get Commercial or Enterprise license. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
Scheduler._external_drag={from_scheduler:null,to_scheduler:null,drag_data:null,drag_placeholder:null,delete_dnd_holder:function(){var e=this.drag_placeholder;e&&(e.parentNode&&e.parentNode.removeChild(e),document.body.className=document.body.className.replace(" dhx_no_select",""),this.drag_placeholder=null)},copy_event_node:function(e,t){for(var n=null,a=0;a<t._rendered.length;a++){var d=t._rendered[a];if(d.getAttribute("event_id")==e.id||d.getAttribute("event_id")==t._drag_id){n=d.cloneNode(!0),
n.style.position=n.style.top=n.style.left="";break}}return n||document.createElement("div")},create_dnd_holder:function(e,t){if(this.drag_placeholder)return this.drag_placeholder;var n=document.createElement("div"),a=t.templates.event_outside(e.start_date,e.end_date,e);return a?n.innerHTML=a:n.appendChild(this.copy_event_node(e,t)),n.className="dhx_drag_placeholder",n.style.position="absolute",this.drag_placeholder=n,document.body.appendChild(n),document.body.className+=" dhx_no_select",n},move_dnd_holder:function(e){
var t={x:e.clientX,y:e.clientY};if(this.create_dnd_holder(this.drag_data.ev,this.from_scheduler),this.drag_placeholder){var n=t.x,a=t.y,d=document.documentElement,r=document.body,i=this.drag_placeholder;i.style.left=10+n+(d&&d.scrollLeft||r&&r.scrollLeft||0)-(d.clientLeft||0)+"px",i.style.top=10+a+(d&&d.scrollTop||r&&r.scrollTop||0)-(d.clientTop||0)+"px"}},clear_scheduler_dnd:function(e){e._drag_id=e._drag_mode=e._drag_event=e._new_event=null},stop_drag:function(e){e&&this.clear_scheduler_dnd(e),
this.delete_dnd_holder(),this.drag_data=null},inject_into_scheduler:function(e,t,n){e._count=1,e._sorder=0,e.event_pid&&"0"!=e.event_pid&&(e.event_pid=null,e.rec_type=e.rec_pattern="",e.event_length=0),t._drag_event=e,t._events[e.id]=e,t._drag_id=e.id,t._drag_mode="move",n&&t._on_mouse_move(n)},start_dnd:function(e){if(e.config.drag_out){this.from_scheduler=e,this.to_scheduler=e;var t=this.drag_data={};t.ev=e._drag_event,t.orig_id=e._drag_event.id}},land_into_scheduler:function(e,t){if(!e.config.drag_in)return this.move_dnd_holder(t),
!1;var n=this.drag_data,a=e._lame_clone(n.ev);if(e!=this.from_scheduler){a.id=e.uid();var d=a.end_date-a.start_date;a.start_date=new Date(e.getState().min_date),a.end_date=new Date(a.start_date.valueOf()+d)}else a.id=this.drag_data.orig_id,a._dhx_changed=!0;return this.drag_data.target_id=a.id,e.callEvent("onBeforeEventDragIn",[a.id,a,t])?(this.to_scheduler=e,this.inject_into_scheduler(a,e,t),this.delete_dnd_holder(),e.updateView(),e.callEvent("onEventDragIn",[a.id,a,t]),!0):!1},drag_from_scheduler:function(e,t){
if(this.drag_data&&e._drag_id&&e.config.drag_out){if(this.to_scheduler==e&&(this.to_scheduler=null),!e.callEvent("onBeforeEventDragOut",[e._drag_id,e._drag_event,t]))return!1;this.create_dnd_holder(this.drag_data.ev,e);var n=e._drag_id;return this.drag_data.target_id=null,delete e._events[n],this.clear_scheduler_dnd(e),e.updateEvent(n),e.callEvent("onEventDragOut",[n,this.drag_data.ev,t]),!0}return!1},reset_event:function(e,t){this.inject_into_scheduler(e,t),this.stop_drag(t),t.updateView()},move_permanently:function(e,t,n,a){
a.callEvent("onEventAdded",[t.id,t]),this.inject_into_scheduler(e,n),this.stop_drag(n),e.event_pid&&"0"!=e.event_pid?(n.callEvent("onConfirmedBeforeEventDelete",[e.id]),n.updateEvent(t.event_pid)):n.deleteEvent(e.id),n.updateView(),a.updateView()}},dhtmlxEvent(window,"load",function(){dhtmlxEvent(document.body,"mousemove",function(e){var t=Scheduler._external_drag,n=t.target_scheduler;if(n)if(t.from_scheduler)if(n._drag_id);else{var a=t.to_scheduler;(!a||t.drag_from_scheduler(a,e))&&t.land_into_scheduler(n,e);

}else"move"==n.getState().drag_mode&&n.config.drag_out&&t.start_dnd(n);else t.from_scheduler&&(t.to_scheduler?t.drag_from_scheduler(t.to_scheduler,e):t.move_dnd_holder(e));t.target_scheduler=null}),dhtmlxEvent(document.body,"mouseup",function(e){var t=Scheduler._external_drag,n=t.from_scheduler,a=t.to_scheduler;if(n)if(a&&n==a)n.updateEvent(t.drag_data.target_id);else if(a&&n!==a){var d=t.drag_data.ev,r=a.getEvent(t.drag_data.target_id);n.callEvent("onEventDropOut",[d.id,d,a,e])?t.move_permanently(d,r,n,a):t.reset_event(d,n);

}else{var d=t.drag_data.ev;n.callEvent("onEventDropOut",[d.id,d,null,e])&&t.reset_event(d,n)}t.stop_drag(),t.current_scheduler=t.from_scheduler=t.to_scheduler=null})}),Scheduler.plugin(function(e){e.config.drag_in=!0,e.config.drag_out=!0,e.templates.event_outside=function(e,t,n){};var t=Scheduler._external_drag;e.attachEvent("onTemplatesReady",function(){dhtmlxEvent(e._obj,"mousemove",function(n){t.target_scheduler=e}),dhtmlxEvent(e._obj,"mouseup",function(n){t.target_scheduler=e})})});