/*
@license
dhtmlxScheduler.Net v.3.3.0 

This software is covered by DHTMLX Evaluation License. Contact sales@dhtmlx.com to get Commercial or Enterprise license. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
!function(){var e=scheduler.createTimelineView;scheduler.createTimelineView=function(t){function a(){var e=new Date(scheduler.getState().date),a=scheduler.date[c+"_start"](e);a=scheduler.date.date_part(a);var n=[],i=scheduler.matrix[c];i.y_unit=n,i.order={};for(var r=0;r<t.days;r++)n.push({key:+a,label:a}),i.order[i.y_unit[r].key]=r,a=scheduler.date.add(a,1,"day")}function n(e){var t={};for(var a in e)t[a]=e[a];return t}function i(e,t){t.setFullYear(e.getFullYear()),t.setMonth(e.getMonth()),t.setDate(e.getDate());

}function r(e){for(var t=[],a=0;a<e.length;a++){var n=_(e[a]);if(scheduler.isOneDayEvent(n))s(n),t.push(n);else{for(var i=new Date(Math.min(+n.end_date,+scheduler._max_date)),r=new Date(Math.max(+n.start_date,+scheduler._min_date)),o=[];+i>+r;){var c=_(n);c.start_date=r,c.end_date=new Date(Math.min(+l(c.start_date),+i)),r=l(r),s(c),t.push(c),o.push(c)}d(o,n)}}return t}function d(e,t){for(var a=!1,n=!1,i=0,r=e.length;r>i;i++){var d=e[i];a=+d._w_start_date==+t.start_date,n=+d._w_end_date==+t.end_date,
d._no_resize_start=d._no_resize_end=!0,a&&(d._no_resize_start=!1),n&&(d._no_resize_end=!1)}}function _(e){var t=scheduler.getEvent(e.event_pid);return t&&t.isPrototypeOf(e)?(e=scheduler._copy_event(e),delete e.event_length,delete e.event_pid,delete e.rec_pattern,delete e.rec_type):e=scheduler._lame_clone(e),e}function s(e){if(!e._w_start_date||!e._w_end_date){var t=scheduler.date,a=e._w_start_date=new Date(e.start_date),n=e._w_end_date=new Date(e.end_date);e[h]=+t.date_part(e.start_date),e._count||(e._count=1),
e._sorder||(e._sorder=0);var i=n-a;e.start_date=new Date(scheduler._min_date),o(a,e.start_date),e.end_date=new Date(+e.start_date+i)}}function o(e,t){t.setMinutes(e.getMinutes()),t.setHours(e.getHours())}function l(e){var t=scheduler.date.add(e,1,"day");return t=scheduler.date.date_part(t)}if("days"!=t.render)return void e.apply(this,arguments);var c=t.name,h=t.y_property="timeline-week"+c;t.y_unit=[],t.render="bar",t.days=t.days||7,e.call(this,t),scheduler.templates[c+"_scalex_class"]=function(){},
scheduler.templates[c+"_scaley_class"]=function(){},scheduler.templates[c+"_scale_label"]=function(e,t,a){return scheduler.templates.day_date(t)},scheduler.date[c+"_start"]=function(e){return e=scheduler.date.week_start(e),e=scheduler.date.add(e,t.x_step*t.x_start,t.x_unit)},scheduler.date["add_"+c]=function(e,a){return scheduler.date.add(e,a*t.days,"day")};var u=scheduler._renderMatrix;scheduler._renderMatrix=function(e,t){e&&a(),u.apply(this,arguments)};var v=scheduler.checkCollision;scheduler.checkCollision=function(e){
if(e[h]){var e=n(e);delete e[h]}return v.apply(scheduler,[e])},scheduler.attachEvent("onBeforeDrag",function(e,t,a){var n=a.target||a.srcElement,i=n.className||"";if("resize"==t)scheduler._w_line_drag_from_start=i.indexOf("dhx_event_resize_end")<0?!0:!1;else if("move"==t&&i.indexOf("no_drag_move")>=0)return!1;return!0});var f=scheduler["mouse_"+c];scheduler["mouse_"+c]=function(e){var t;if(this._drag_event&&(t=this._drag_event._move_delta),void 0===t&&"move"==scheduler._drag_mode){var a=scheduler.matrix[this._mode],n={
y:e.y};scheduler._resolve_timeline_section(a,n);var i=e.x-a.dx,r=new Date(n.section);o(scheduler._timeline_drag_date(a,i),r);var d=scheduler._drag_event,_=this.getEvent(this._drag_id);d._move_delta=(_.start_date-r)/6e4,this.config.preserve_length&&e._ignores&&(d._move_delta=this._get_real_event_length(_.start_date,r,a),d._event_length=this._get_real_event_length(_.start_date,_.end_date,a))}var e=f.apply(scheduler,arguments);if(scheduler._drag_mode&&"move"!=scheduler._drag_mode){var s=null;s=new Date(scheduler._drag_event&&scheduler._drag_event["timeline-week"+c]?scheduler._drag_event["timeline-week"+c]:e.section),
e.y+=Math.round((s-scheduler.date.date_part(new Date(scheduler._min_date)))/(6e4*this.config.time_step)),"resize"==scheduler._drag_mode&&(e.resize_from_start=scheduler._w_line_drag_from_start)}else if(scheduler._drag_event){var l=Math.floor(Math.abs(e.y/(1440/scheduler.config.time_step)));l*=e.y>0?1:-1,e.y=e.y%(1440/scheduler.config.time_step);var h=scheduler.date.date_part(new Date(scheduler._min_date));h.valueOf()!=new Date(e.section).valueOf()&&(e.x=Math.floor((e.section-h)/864e5),e.x+=l)}return e;

},scheduler.attachEvent("onEventCreated",function(e,t){return scheduler._events[e]&&delete scheduler._events[e][h],!0}),scheduler.attachEvent("onBeforeEventChanged",function(e,t,a,n){return scheduler._events[e.id]&&delete scheduler._events[e.id][h],!0});var g=scheduler.render_view_data;scheduler.render_view_data=function(e,t){return this._mode==c&&e&&(e=r(e)),g.apply(scheduler,[e,t])};var m=scheduler.get_visible_events;scheduler.get_visible_events=function(){if(this._mode==c){scheduler._max_date=scheduler.date.date_part(scheduler.date.add(scheduler._min_date,t.days,"day"));

var e=m.apply(scheduler,arguments);return r(e)}return m.apply(scheduler,arguments)};var p=scheduler.addEventNow;scheduler.addEventNow=function(e){if(scheduler.getState().mode==c)if(e[h]){var t=new Date(e[h]);i(t,e.start_date),i(t,e.end_date)}else{var a=new Date(e.start_date);e[h]=+scheduler.date.date_part(a)}return p.apply(scheduler,arguments)};var x=scheduler._render_marked_timespan;scheduler._render_marked_timespan=function(){return scheduler._mode!=c?x.apply(this,arguments):void 0}}}();