//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.EventServices = new HashSet<EventService>();
        }
    
        public int EventId { get; set; }
        public int EventUserId { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Attendance { get; set; }
    
        public virtual EventUser EventUser { get; set; }
        public virtual ICollection<EventService> EventServices { get; set; }
    }
}
