//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventUser
    {
        public EventUser()
        {
            this.Events = new HashSet<Event>();
            this.Services = new HashSet<Service>();
        }
    
        public int EventUserId { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string CompName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Town { get; set; }
        public string County { get; set; }
        public Nullable<int> NumServives { get; set; }
        public Nullable<int> NumEvents { get; set; }
        public string Biog { get; set; }
        public string ImagePath { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<Service> Services { get; set; }
    }
}
