//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.EventServices = new HashSet<EventService>();
        }
    
        public int ServiceId { get; set; }
        public int EventUserId { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public System.TimeSpan FromTime { get; set; }
        public System.TimeSpan ToTime { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
    
        public virtual ICollection<EventService> EventServices { get; set; }
        public virtual EventUser EventUser { get; set; }
    }
}
