/*
@license
dhtmlxScheduler.Net v.3.3.0 

This software is covered by DHTMLX Evaluation License. Contact sales@dhtmlx.com to get Commercial or Enterprise license. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
scheduler.config.multisection=!0,scheduler.config.multisection_shift_all=!0,scheduler.config.section_delemiter=",",scheduler.attachEvent("onSchedulerReady",function(){var e=scheduler._update_unit_section;scheduler._update_unit_section=function(t){return scheduler._update_sections(t,e)};var t=scheduler._update_timeline_section;scheduler._update_timeline_section=function(e){return scheduler._update_sections(e,t)},scheduler.isMultisectionEvent=function(e){if(e&&this._get_multisection_view()){var t=this._get_event_sections(e);

return t.length>1}return!1},scheduler._get_event_sections=function(e){var t=this._get_section_property(),a=e[t]||"";return this._parse_event_sections(a)},scheduler._parse_event_sections=function(e){return e instanceof Array?e:e.toString().split(scheduler.config.section_delemiter)},scheduler._register_copies_array=function(e){for(var t=0;t<e.length;t++)this._register_copy(e[t])},scheduler._register_copy=function(e){this._multisection_copies[e.id]||(this._multisection_copies[e.id]={});var t=e[this._get_section_property()],a=this._multisection_copies[e.id];

a[t]||(a[t]=e)},scheduler._get_copied_event=function(e,t){if(!this._multisection_copies[e])return null;if(this._multisection_copies[e][t])return this._multisection_copies[e][t];var a=this._multisection_copies[e];if(scheduler._drag_event&&scheduler._drag_event._orig_section&&a[scheduler._drag_event._orig_section])return a[scheduler._drag_event._orig_section];var n=1/0,i=null;for(var d in a)a[d]._sorder<n&&(i=a[d],n=a[d]._sorder);return i},scheduler._clear_copied_events=function(){this._multisection_copies={};

},scheduler._clear_copied_events(),scheduler._split_events=function(e){var t=[],a=this._get_multisection_view(),n=this._get_section_property();if(a)for(var i=0;i<e.length;i++){var d=this._get_event_sections(e[i]);if(d.length>1){for(var r=0;r<d.length;r++)if("undefined"!=typeof a.order[d[r]]){var _=this._lame_copy({},e[i]);_[n]=d[r],t.push(_)}}else t.push(e[i])}else t=e;return t},scheduler._get_multisection_view=function(){return this.config.multisection?scheduler._get_section_view():!1};var a=scheduler.get_visible_events;

scheduler.get_visible_events=function(e){this._clear_copied_events();var t=a.apply(this,arguments);if(this._get_multisection_view()){t=this._split_events(t);for(var n=0;n<t.length;n++)this.is_visible_events(t[n])||(t.splice(n,1),n--);this._register_copies_array(t)}return t},scheduler._rendered_events={};var n=scheduler.render_view_data;scheduler.render_view_data=function(e,t){return this._get_multisection_view()&&e&&(e=this._split_events(e),this._restore_render_flags(e)),n.apply(this,[e,t])},scheduler._restore_render_flags=function(e){
for(var t=this._get_section_property(),a=0;a<e.length;a++){var n=e[a],i=scheduler._get_copied_event(n.id,n[t]);if(i)for(var d in i)0===d.indexOf("_")&&(n[d]=i[d])}},scheduler._update_sections=function(e,t){var a=e.view,n=e.event,i=e.pos;if(scheduler.isMultisectionEvent(n)){if(scheduler._drag_event._orig_section||(scheduler._drag_event._orig_section=i.section),scheduler._drag_event._orig_section!=i.section){var d=a.order[i.section]-a.order[scheduler._drag_event._orig_section];if(d){var r=this._get_event_sections(n),_=[],s=!0;

if(scheduler.config.multisection_shift_all)for(var o=0;o<r.length;o++){var l=scheduler._shift_sections(a,r[o],d);if(null===l){_=r,s=!1;break}_[o]=l}else for(var o=0;o<r.length;o++){if(r[o]==i.section){_=r,s=!1;break}if(r[o]==scheduler._drag_event._orig_section){var l=scheduler._shift_sections(a,r[o],d);if(null===l){_=r,s=!1;break}_[o]=l}else _[o]=r[o]}s&&(scheduler._drag_event._orig_section=i.section),n[scheduler._get_section_property()]=_.join(",")}}}else t.apply(scheduler,[e])},scheduler._shift_sections=function(e,t,a){
for(var n=null,i=e.y_unit,d=0;d<i.length;d++)if(i[d].key==t){n=d;break}var r=i[n+a];return r?r.key:null};var i=scheduler._get_blocked_zones;scheduler._get_blocked_zones=function(e,t,a,n,d){if(t&&this.config.multisection){t=this._parse_event_sections(t);for(var r=[],_=0;_<t.length;_++)r=r.concat(i.apply(this,[e,t[_],a,n,d]));return r}return i.apply(this,arguments)};var d=scheduler._check_sections_collision;scheduler._check_sections_collision=function(e,t){if(this.config.multisection&&this._get_section_view()){
e=this._split_events([e]),t=this._split_events([t]);for(var a=!1,n=0,i=e.length;i>n&&!a;n++)for(var r=0,_=t.length;_>r;r++)if(d.apply(this,[e[n],t[r]])){a=!0;break}return a}return d.apply(this,arguments)}});