/*
@license
dhtmlxScheduler.Net v.3.3.0 

This software is covered by DHTMLX Evaluation License. Contact sales@dhtmlx.com to get Commercial or Enterprise license. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
Scheduler.plugin(function(e){!function(){e._grid={sort_rules:{"int":function(e,t,a){return 1*a(e)<1*a(t)?1:-1},str:function(e,t,a){return a(e)<a(t)?1:-1},date:function(e,t,a){return new Date(a(e))<new Date(a(t))?1:-1}},_getObjName:function(e){return"grid_"+e},_getViewName:function(e){return e.replace(/^grid_/,"")}}}(),e.createGridView=function(t){function a(e){return!(void 0!==e&&(1*e!=e||0>e))}var n=t.name||"grid",d=e._grid._getObjName(n);e.config[n+"_start"]=t.from||new Date(0),e.config[n+"_end"]=t.to||new Date(9999,1,1),
e[d]=t,e[d].defPadding=8,e[d].columns=e[d].fields,e[d].unit=t.unit||"month",e[d].step=t.step||1,delete e[d].fields;for(var i=e[d].columns,r=0;r<i.length;r++)a(i[r].width)&&(i[r].initialWidth=i[r].width),a(i[r].paddingLeft)||delete i[r].paddingLeft,a(i[r].paddingRight)||delete i[r].paddingRight;e[d].select=void 0===t.select?!0:t.select,void 0===e.locale.labels[n+"_tab"]&&(e.locale.labels[n+"_tab"]=e[d].label||e.locale.labels.grid_tab),e[d]._selected_divs=[],e.date[n+"_start"]=function(a){return e.date[t.unit+"_start"]?e.date[t.unit+"_start"](a):a;

},e.date["add_"+n]=function(t,a){return e.date.add(t,a*e[d].step,e[d].unit)},e.templates[n+"_date"]=function(t,a){return e.templates.day_date(t)+" - "+e.templates.day_date(a)},e.templates[n+"_full_date"]=function(t,a,d){return e.isOneDayEvent(d)?this[n+"_single_date"](t):e.templates.day_date(t)+" &ndash; "+e.templates.day_date(a)},e.templates[n+"_single_date"]=function(t){return e.templates.day_date(t)+" "+this.event_date(t)},e.templates[n+"_field"]=function(e,t){return t[e]},e.attachEvent("onTemplatesReady",function(){
e.attachEvent("onDblClick",function(t,a){return this._mode==n?(e._click.buttons.details(t),!1):!0}),e.attachEvent("onClick",function(t,a){return this._mode==n&&e[d].select?(e._grid.unselectEvent("",n),e._grid.selectEvent(t,n,a),!1):!0});var t=e.render_data;e.render_data=function(a){return this._mode!=n?t.apply(this,arguments):void e._grid._fill_grid_tab(d)};var a=e.render_view_data;e.render_view_data=function(){var t=e._els.dhx_cal_data[0].lastChild;return this._mode==n&&t&&(e._grid._gridScrollTop=t.scrollTop),
a.apply(this,arguments)}}),e[n+"_view"]=function(t){if(e._grid._sort_marker=null,delete e._gridView,e._grid._gridScrollTop=0,e._rendered=[],e[d]._selected_divs=[],t){var a=null,i=null,r=e[d];r.paging?(a=e.date[n+"_start"](new Date(e._date)),i=e.date["add_"+n](a,1)):(a=e.config[n+"_start"],i=e.config[n+"_end"]),e._min_date=a,e._max_date=i,e._grid.set_full_view(d);var _="";+a>+new Date(0)&&+i<+new Date(9999,1,1)&&(_=e.templates[n+"_date"](a,i)),e._els.dhx_cal_date[0].innerHTML=_,e._gridView=d}}},e.dblclick_dhx_grid_area=function(){
!this.config.readonly&&this.config.dblclick_create&&this.addEventNow()},e._click.dhx_cal_header&&(e._old_header_click=e._click.dhx_cal_header),e._click.dhx_cal_header=function(t){if(e._gridView){var a=t||window.event,n=e._grid.get_sort_params(a,e._gridView);e._grid.draw_sort_marker(a.originalTarget||a.srcElement,n.dir),e.clear_view(),e._grid._fill_grid_tab(e._gridView,n)}else if(e._old_header_click)return e._old_header_click.apply(this,arguments)},e._grid.selectEvent=function(t,a,n){if(e.callEvent("onBeforeRowSelect",[t,n])){
var d=e._grid._getObjName(a);e.for_rendered(t,function(t){t.className+=" dhx_grid_event_selected",e[d]._selected_divs.push(t)}),e._select_id=t}},e._grid._unselectDiv=function(e){e.className=e.className.replace(/ dhx_grid_event_selected/,"")},e._grid.unselectEvent=function(t,a){var n=e._grid._getObjName(a);if(n&&e[n]._selected_divs)if(t){for(var d=0;d<e[n]._selected_divs.length;d++)if(e[n]._selected_divs[d].getAttribute("event_id")==t){e._grid._unselectDiv(e[n]._selected_divs[d]),e[n]._selected_divs.slice(d,1);

break}}else{for(var d=0;d<e[n]._selected_divs.length;d++)e._grid._unselectDiv(e[n]._selected_divs[d]);e[n]._selected_divs=[]}},e._grid.get_sort_params=function(t,a){var n=t.originalTarget||t.srcElement,d="desc";"dhx_grid_view_sort"==n.className&&(n=n.parentNode),n.className&&-1!=n.className.indexOf("dhx_grid_sort_asc")||(d="asc");for(var i=0,r=0;r<n.parentNode.childNodes.length;r++)if(n.parentNode.childNodes[r]==n){i=r;break}var _=null;if(e[a].columns[i].template){var l=e[a].columns[i].template;_=function(e){
return l(e.start_date,e.end_date,e)}}else{var o=e[a].columns[i].id;"date"==o&&(o="start_date"),_=function(e){return e[o]}}var s=e[a].columns[i].sort;return"function"!=typeof s&&(s=e._grid.sort_rules[s]||e._grid.sort_rules.str),{dir:d,value:_,rule:s}},e._grid.draw_sort_marker=function(t,a){"dhx_grid_view_sort"==t.className&&(t=t.parentNode),e._grid._sort_marker&&(e._grid._sort_marker.className=e._grid._sort_marker.className.replace(/( )?dhx_grid_sort_(asc|desc)/,""),e._grid._sort_marker.removeChild(e._grid._sort_marker.lastChild)),
t.className+=" dhx_grid_sort_"+a,e._grid._sort_marker=t;var n="<div class='dhx_grid_view_sort' style='left:"+(+t.style.width.replace("px","")-15+t.offsetLeft)+"px'>&nbsp;</div>";t.innerHTML+=n},e._grid.sort_grid=function(t){var t=t||{dir:"desc",value:function(e){return e.start_date},rule:e._grid.sort_rules.date},a=e.get_visible_events();return a.sort("desc"==t.dir?function(e,a){return t.rule(e,a,t.value)}:function(e,a){return-t.rule(e,a,t.value)}),a},e._grid.set_full_view=function(t){if(t){var a=(e.locale.labels,
e._grid._print_grid_header(t));e._els.dhx_cal_header[0].innerHTML=a,e._table_view=!0,e.set_sizes()}},e._grid._calcPadding=function(t,a){var n=(void 0!==t.paddingLeft?1*t.paddingLeft:e[a].defPadding)+(void 0!==t.paddingRight?1*t.paddingRight:e[a].defPadding);return n},e._grid._getStyles=function(e,t){for(var a=[],n="",d=0;t[d];d++)switch(n=t[d]+":",t[d]){case"text-align":e.align&&a.push(n+e.align);break;case"vertical-align":e.valign&&a.push(n+e.valign);break;case"padding-left":void 0!==e.paddingLeft&&a.push(n+(e.paddingLeft||"0")+"px");

break;case"padding-right":void 0!==e.paddingRight&&a.push(n+(e.paddingRight||"0")+"px")}return a},e._grid._fill_grid_tab=function(t,a){for(var n=(e._date,e._grid.sort_grid(a)),d=e[t].columns,i="<div>",r=-2,_=0;_<d.length;_++){var l=e._grid._calcPadding(d[_],t);r+=d[_].width+l,_<d.length-1&&(i+="<div class='dhx_grid_v_border' style='left:"+r+"px'></div>")}i+="</div>",i+="<div class='dhx_grid_area'><table>";for(var _=0;_<n.length;_++)i+=e._grid._print_event_row(n[_],t);i+="</table></div>",e._els.dhx_cal_data[0].innerHTML=i,
e._els.dhx_cal_data[0].lastChild.scrollTop=e._grid._gridScrollTop||0;var o=e._els.dhx_cal_data[0].getElementsByTagName("tr");e._rendered=[];for(var _=0;_<o.length;_++)e._rendered[_]=o[_]},e._grid._print_event_row=function(t,a){var n=[];t.color&&n.push("background:"+t.color),t.textColor&&n.push("color:"+t.textColor),t._text_style&&n.push(t._text_style),e[a].rowHeight&&n.push("height:"+e[a].rowHeight+"px");var d="";n.length&&(d="style='"+n.join(";")+"'");for(var i=e[a].columns,r=e.templates.event_class(t.start_date,t.end_date,t),_="<tr class='dhx_grid_event"+(r?" "+r:"")+"' event_id='"+t.id+"' "+d+">",l=e._grid._getViewName(a),o=["text-align","vertical-align","padding-left","padding-right"],s=0;s<i.length;s++){
var c;c=i[s].template?i[s].template(t.start_date,t.end_date,t):"date"==i[s].id?e.templates[l+"_full_date"](t.start_date,t.end_date,t):"start_date"==i[s].id||"end_date"==i[s].id?e.templates[l+"_single_date"](t[i[s].id]):e.templates[l+"_field"](i[s].id,t);var h=e._grid._getStyles(i[s],o),u=i[s].css?' class="'+i[s].css+'"':"";_+="<td style='width:"+i[s].width+"px;"+h.join(";")+"' "+u+">"+c+"</td>"}return _+="<td class='dhx_grid_dummy'></td></tr>"},e._grid._print_grid_header=function(t){for(var a="<div class='dhx_grid_line'>",n=e[t].columns,d=[],i=n.length,r=e._obj.clientWidth-2*n.length-20,_=0;_<n.length;_++){
var l=1*n[_].initialWidth;isNaN(l)||""===n[_].initialWidth||null===n[_].initialWidth||"boolean"==typeof n[_].initialWidth?d[_]=null:(i--,r-=l,d[_]=l)}for(var o=Math.floor(r/i),s=["text-align","padding-left","padding-right"],c=0;c<n.length;c++){var h=d[c]?d[c]:o;n[c].width=h-e._grid._calcPadding(n[c],t);var u=e._grid._getStyles(n[c],s);a+="<div style='width:"+(n[c].width-1)+"px;"+u.join(";")+"'>"+(void 0===n[c].label?n[c].id:n[c].label)+"</div>"}return a+="</div>"}});